config/routes.rb
Rails.application.routes.draw do
  resources :surveys
    root 'surveys#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :question
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question, optional: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey, optional: true
  has_many :options, dependent: :destroy
  accepts_nested_attributes_for :options, allow_destroy: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :feedback, :question
end

app/models/survey.rb
class Survey < ApplicationRecord
	has_many :questions, dependent: :destroy
	accepts_nested_attributes_for :questions, allow_destroy: true, reject_if: :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ]

  # GET /surveys or /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    @survey.questions.build
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully created." }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy


    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:name, :description, questions_attributes:[:id, :title, :type, :survey_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, form, association)
		new_object = form.object.send(association).klass.new
		id = new_object.object_id
		fields = form.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_fields", form: builder)
		end
		link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n","")})
	end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/surveys/_form.html.erb
<%= form_for @survey do |form| %>
  <% if survey.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="form-group">
    <%= form.label :name, "1) Your Name:", style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, "2) Your Surname:", style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div> -->

  <!-- <div class="form-group">
    <%= form.fields_for :questions do |question| %>

      <%= question.label :id %><br>
      <%= question.text_field :id %><br>
      <%= question.label :title %><br>
      <%= question.text_field :title %><br>
      <%= question.label :type %><br>
      <%= question.text_field :type %><br>
      <%= question.label :survey_id %><br>
      <%= question.text_field :survey_id %><br>

      <%= question.remove_nested_fields_link %>
      
    <% end %>

      <%= form.add_nested_fields_link :questions %>
  </div>  --> 

  <div class="nested-fields">
    <%= form.hidden_field :_destroy %>
    <div>
      <%= form.label :id %>
      <%= form.text_field :id, class: "form-control" %><br>
    </div>

    <div>
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %><br>
    </div>
    <!-- <div>
      <%= form.label :description %>
      <%= form.text_field :description, class: "form-control" %><br>
    </div> -->
   
    <div class="form-group">
      <%= form.label :name, "3) How was your experience with us today?" %><br />
      <%= form.radio_button :name, true %>
      <%= form.label :autolyse, "Very Good", :value => "1"  %><br>
      <%= form.radio_button :autolyse, false, :checked => true %>
      <%= form.label :autolyse, "Good", :value => "2" %><br>
      <%= form.radio_button :autolyse, false, :checked => true %>
      <%= form.label :autolyse, "Neutral", :value => "3" %><br>
      <%= form.radio_button :autolyse, false, :checked => true %>
      <%= form.label :autolyse, "Bad", :value => "4" %><br>
      <%= form.radio_button :autolyse, false, :checked => true %>
      <%= form.label :autolyse, "Very Bad", :value => "5" %><br>
      <%= form.label :text, "Please explain the reason for your choice : ", style: "display: block" %>
      <%= form.text_field :description, class: "form-control" %>
    </div>

    <div>
      <%= link_to "Add", '#', class: "add_fields" %><br>
      <%= link_to "Remove", '#', class: "remove_fields" %><br>
    </div>

  </div>

  <div>
    <br>
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/_survey.html.erb
<div id="<%= dom_id survey %>">

  
  <p>
    <strong>1) Your Name:</strong>
    <%= survey.name %>
  </p>

  <p>
    <strong>3) Your Reason:</strong>
    <%= survey.description %>
  </p>

   <p>
    <strong>4) Test:</strong>
    <%= survey.questions %>
  </p>


</div>

app/views/surveys/edit.html.erb
<div class="container">
<h1>Editing survey</h1>

<%= render "form", survey: @survey %>

<br>

<div>
  <%= link_to "Show this survey", @survey %> |
  <%= link_to "Back to surveys", surveys_path %>
</div>
</div>

app/views/surveys/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Surveys</h1>

<div id="surveys">
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Survey ID</th>
      <th>User Name</th>
      <th>Options</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>  
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.id %></td>
        <td><%= survey.name %></td>
        <td><%= link_to "Show this survey", survey %></td> 
      </tr>
      <% end %>
   </tbody>
  </table>
</div>

<%= link_to "New survey", new_survey_path %>

app/views/surveys/new.html.erb
<div class="container">
<h1>New survey</h1>

<%= render "form", survey: @survey %>

<br>

<div>
  <%= link_to "Back to surveys", surveys_path %>
</div>
</div>

app/views/surveys/show.html.erb
<div class="container">
<p style><%= notice %></p>

<%= render @survey %>

<div>
  <%= link_to "Edit this survey", edit_survey_path(@survey) %> |
  <%= link_to "Back to surveys", surveys_path %>

  <%= button_to "Destroy this survey", @survey, method: :delete %>
</div>
</div>